apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: ""
    field.cattle.io/publicEndpoints: '[{"port":8888,"protocol":"TCP","serviceName":"default:eos-node-nodeport","allNodes":true},{"addresses":["192.168.0.42"],"port":9876,"protocol":"TCP","serviceName":"default:eos-node-nodeport","allNodes":true}]'
  creationTimestamp: 2018-12-17T12:10:47Z
  generation: 8
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-eos-node
  name: eos-node
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-eos-node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8888,"dnsName":"eos-node-nodeport","kind":"NodePort","name":"8888tcp88881","protocol":"TCP","sourcePort":8888},{"containerPort":9876,"dnsName":"eos-node-nodeport","kind":"NodePort","name":"9876tcp98761","protocol":"TCP","sourcePort":9876}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-eos-node
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: eos-mainet
            optional: false
        image: leochan007/eos
        imagePullPolicy: Always
        name: eos-node
        ports:
        - containerPort: 8888
          name: 8888tcp88881
          protocol: TCP
        - containerPort: 9876
          name: 9876tcp98761
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /root/data
          name: data-path
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/eos/data
          type: ""
        name: data-path
