prepare:
	npm i -s axios vuex vuetify vue-i18n echarts moment
	npm i -d vue-style-loader css-loader sass-loader
	#npm audit fix --force

run_local:
	npm start

run_testnet:
	TESTNET=testnet npm start

build_testnet:
	TESTNET=testnet npm run build

build_testnet_stg:
	TESTNET=testnet_stg npm run build

build_prod:
	npm run build
