apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: ""
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-aci-frontend
  name: aci-frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-aci-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"aci-frontend-nodeport","kind":"NodePort","name":"80tcp300031","protocol":"TCP","sourcePort":30003}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-aci-frontend
    spec:
      imagePullSecrets:
      - name: nexus
      containers:
      - image: repo.alphacario.com:8090/aci-frontend:v1
        imagePullPolicy: Always
        name: aci-frontend
        ports:
        - containerPort: 80
          name: 80tcp300031
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
